### ISSUE TITLE
Оформление кода программы

### ISSUE THREAD

**Issue by laralex** [ParkhomenkoV/SPbPU-student-thesis-template#2]
Я использую `\usepackage{listings}` для создания листингов, и когда передаю параметр caption в листинг, название появляется по центру, а не рядом с надписью `Листинг 1.1`. Полагаю, что раз надпись `Листинг` появляется, то это заложено шаблоном, но является ли такое оформление правильным по стандарту оформления ГИА?

![image](https://user-images.githubusercontent.com/20727983/81194478-5d029100-8fc5-11ea-9a7f-395db45b1a2a.png)

Также, есть ли какой-то пример, как вообще оформлять листинги, или это на наше усмотрение (в положении ГИА вроде ничего не указано). Просто хочется сделать шрифт мельче 14 и междустрочное расстояние минимальным, для компактности.

Мой глобальный стиль листингов
```
\lstset{
	columns=fullflexible,
	basicstyle=\linespread{0.7}\fontsize{11}{13}\selectfont\ttfamily, 
	language=[Sharp]C,
	resetmargins=true,
	literate={\ \ }{{\ }}1,
	morecomment=[is]{\#\%}{\#:},
	breaklines=true,
	stepnumber=5,
	numberstyle=\tiny\color{black},
	keywordstyle=\color{NavyBlue},
	extendedchars=true,
	breakautoindent=true,
	prebreak=\raisebox{0ex}[0ex][0ex]{\ensuremath{\hookrightarrow}}, 
	breakindent=100pt,
	numberstyle=\scriptsize
}
```
и локальный для приведенного на картинке листинга

```
\begin{lstlisting}[
	language=XML,
	numbers=none,
	caption={Пример содержания файла-манифеста с моделями деталей},
	morekeywords={encoding,models,group,name,src,type,model},
	basicstyle=\fontsize{12}{12}\selectfont\ttfamily,
	label={code:manifest},
]

...
\end{lstlisting}
```

**Comment by ParkhomenkoV** [comment]
@laralex, спасибо за вопрос. Листинги нельзя использовать в тексте ВКР с помощью данного окружения. Упаковываем всё в figure или minipage.

Причин несколько. 
1. Данное окружение ещё официально не принято в российских ГОСТах.
2. Фактически мы видим некоторую синтактическо-графическую структуру, оформленную в отличном от основного текста требованиях, включая
2.1. шрифт
2.2. цвет шрифта
2.3. отсутствие предложений, оформленных по правилам русского языка
2.4. как правило горизонтальные линии с подсчетом номеров строк 

-

**Comment by laralex** [comment]
Можно ли в приложении не делать код рисунками? Т.к. возникают проблемы, если листинг больше одной страницы, то он как рисунок не разделяется, да и обрабатывать 70 страниц не очень удобно.

В текущем моем варианте я могу за одну строчку включить файл с кодом целиком, например, `\lstinputlisting[caption={Asset.cs}]{./Asset.cs}` и он как текст идеально разбивается на страницы и заполняет место, только подпись "Листинг" вместо "Рис."

**Comment by ParkhomenkoV** [comment]
@laralex, да, конечно! В приложении можно использовать листинги. Там более мягкие требования к оформлению.
